apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: demo
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
      restartPolicy: Always
