apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: my-app-2.0
    env: prod
spec:
  type: LoadBalancer
  selector:
      app: my-app-2.0
  ports:
    - port: 80
      targetPort: 80 