apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxv1
  labels:
    deploy: canary
spec:
  replicas: 3
  selector:
    matchLabels: 
      deploy: canary
  template:
    metadata:
      labels:
        deploy: canary
    spec:
      containers:
      - name: nginx-cont
        image: nginx:latest
        ports:
        - containerPort: 80
