apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxv2
  labels:
    deploy: canary
spec:
  replicas: 3
  selector:
    matchLabels: 
      deploy: canary
  template:    
      metadata:
        labels:
          deploy: canary
      spec:    
        containers:
        - name: green-cont
          image: anshuldevops/magicalnginx:latest
          ports:
          - containerPort: 80