apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: demo-app
spec:
  containers:
  - name: my-container
    image: busybox:latest
    command:
    - "/bin/sh"
    - "-c"
    - echo Hello this is my container
    ports:
    - containerPort: 80
  restartPolicy: Never

    