apiVersion: v1
kind: Pod
metadata: 
    name: busybox
    namespace: default
spec:
  containers:
  - name: busybox-pod
    image: busybox

  restartPolicy: Never

  #docker version of the file
  #FROM scratch
  #ADD busybox.tar.gz /
  #CMD ["sh"]