apiVersion: v1
kind: Pod
metadata:
  name: busybox-updated
  namespace: default
spec:
  containers:
  - name: busybox-pod-v1
    image: busybox
    command:
      - sleep
      - "3600"
  restartPolicy: Always