apiVersion: v1
kind: Pod
metadata: 
  name: debian-command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: debian-container
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure