apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    purpose: demo-multi-container
spec:
  containers:
  - name: nginx-pod
    image: nginx:latest

  - name: busybox-pod
    image: busybox
    command:
    - sleep
    - "3600"